import {
  DomainGroup,
  HandleGroup,
  EmailThread,
  ChatMessage,
  Folder,
  AIChatMessage,
} from "./types";

export const mockDomainGroups: DomainGroup[] = [
  {
    id: "google.com",
    domain: "google.com",
    totalCount: 435,
    unreadCount: 28,
    lastReceivedAt: new Date("2026-04-27T08:30:00"),
    status: "active",
  },
  {
    id: "facebook.com",
    domain: "facebook.com",
    totalCount: 600,
    unreadCount: 142,
    lastReceivedAt: new Date("2026-04-27T07:15:00"),
    status: "active",
  },
  {
    id: "x.com",
    domain: "x.com",
    totalCount: 900,
    unreadCount: 310,
    lastReceivedAt: new Date("2026-04-27T06:45:00"),
    status: "active",
  },
  {
    id: "stripe.com",
    domain: "stripe.com",
    totalCount: 87,
    unreadCount: 5,
    lastReceivedAt: new Date("2026-04-26T14:20:00"),
    status: "active",
  },
  {
    id: "github.com",
    domain: "github.com",
    totalCount: 234,
    unreadCount: 56,
    lastReceivedAt: new Date("2026-04-27T09:00:00"),
    status: "active",
  },
  {
    id: "amazon.com",
    domain: "amazon.com",
    totalCount: 156,
    unreadCount: 23,
    lastReceivedAt: new Date("2026-04-26T22:10:00"),
    status: "active",
  },
  {
    id: "linkedin.com",
    domain: "linkedin.com",
    totalCount: 342,
    unreadCount: 89,
    lastReceivedAt: new Date("2026-04-27T05:30:00"),
    status: "muted",
  },
  {
    id: "notion.so",
    domain: "notion.so",
    totalCount: 45,
    unreadCount: 2,
    lastReceivedAt: new Date("2026-04-25T11:00:00"),
    status: "active",
  },
  {
    id: "vercel.com",
    domain: "vercel.com",
    totalCount: 32,
    unreadCount: 8,
    lastReceivedAt: new Date("2026-04-27T10:15:00"),
    status: "active",
  },
  {
    id: "figma.com",
    domain: "figma.com",
    totalCount: 19,
    unreadCount: 1,
    lastReceivedAt: new Date("2026-04-24T16:45:00"),
    status: "active",
  },
];

export const mockHandleGroups: Record<string, HandleGroup[]> = {
  "google.com": [
    {
      id: "ravi@google.com",
      domainId: "google.com",
      email: "ravi@google.com",
      name: "Ravi Krishnan",
      totalCount: 30,
      unsubscribeMethod: "none",
    },
    {
      id: "priya@google.com",
      domainId: "google.com",
      email: "priya@google.com",
      name: "Priya Sharma",
      totalCount: 15,
      unsubscribeMethod: "header",
      unsubscribeUrl: "https://google.com/unsubscribe",
    },
    {
      id: "jack@google.com",
      domainId: "google.com",
      email: "jack@google.com",
      name: "Jack Thompson",
      totalCount: 3,
      unsubscribeMethod: "none",
    },
    {
      id: "notifications@google.com",
      domainId: "google.com",
      email: "notifications@google.com",
      name: "Google Notifications",
      totalCount: 200,
      unsubscribeUrl: "https://google.com/notifications/unsubscribe",
      unsubscribeMethod: "footer_link",
    },
    {
      id: "cloud-noreply@google.com",
      domainId: "google.com",
      email: "cloud-noreply@google.com",
      name: "Google Cloud",
      totalCount: 187,
      unsubscribeUrl: "https://cloud.google.com/notifications/unsubscribe",
      unsubscribeMethod: "header",
    },
  ],
  "facebook.com": [
    {
      id: "mark@facebook.com",
      domainId: "facebook.com",
      email: "mark@facebook.com",
      name: "Mark Zuckerberg",
      totalCount: 5,
      unsubscribeMethod: "none",
    },
    {
      id: "notifications@facebook.com",
      domainId: "facebook.com",
      email: "notifications@facebook.com",
      name: "Facebook Notifications",
      totalCount: 450,
      unsubscribeUrl: "https://facebook.com/settings/notifications",
      unsubscribeMethod: "footer_link",
    },
    {
      id: "meta-business@facebook.com",
      domainId: "facebook.com",
      email: "meta-business@facebook.com",
      name: "Meta Business",
      totalCount: 145,
      unsubscribeUrl: "https://business.facebook.com/notifications",
      unsubscribeMethod: "header",
    },
  ],
  "x.com": [
    {
      id: "notifications@x.com",
      domainId: "x.com",
      email: "notifications@x.com",
      name: "X Notifications",
      totalCount: 750,
      unsubscribeUrl: "https://x.com/settings/notifications",
      unsubscribeMethod: "header",
    },
    {
      id: "digest@x.com",
      domainId: "x.com",
      email: "digest@x.com",
      name: "X Digest",
      totalCount: 150,
      unsubscribeUrl: "https://x.com/settings/digest",
      unsubscribeMethod: "footer_link",
    },
  ],
  "stripe.com": [
    {
      id: "receipts@stripe.com",
      domainId: "stripe.com",
      email: "receipts@stripe.com",
      name: "Stripe Receipts",
      totalCount: 42,
      unsubscribeMethod: "none",
    },
    {
      id: "updates@stripe.com",
      domainId: "stripe.com",
      email: "updates@stripe.com",
      name: "Stripe Updates",
      totalCount: 25,
      unsubscribeUrl: "https://stripe.com/communications/unsubscribe",
      unsubscribeMethod: "header",
    },
    {
      id: "support@stripe.com",
      domainId: "stripe.com",
      email: "support@stripe.com",
      name: "Stripe Support",
      totalCount: 20,
      unsubscribeMethod: "none",
    },
  ],
  "github.com": [
    {
      id: "notifications@github.com",
      domainId: "github.com",
      email: "notifications@github.com",
      name: "GitHub Notifications",
      totalCount: 180,
      unsubscribeUrl: "https://github.com/settings/notifications",
      unsubscribeMethod: "header",
    },
    {
      id: "noreply@github.com",
      domainId: "github.com",
      email: "noreply@github.com",
      name: "GitHub NoReply",
      totalCount: 54,
      unsubscribeMethod: "none",
    },
  ],
  "amazon.com": [
    {
      id: "ship-confirm@amazon.com",
      domainId: "amazon.com",
      email: "ship-confirm@amazon.com",
      name: "Amazon Shipping",
      totalCount: 67,
      unsubscribeMethod: "none",
    },
    {
      id: "deals@amazon.com",
      domainId: "amazon.com",
      email: "deals@amazon.com",
      name: "Amazon Deals",
      totalCount: 89,
      unsubscribeUrl: "https://amazon.com/gp/communications/unsubscribe",
      unsubscribeMethod: "footer_link",
    },
  ],
  "linkedin.com": [
    {
      id: "notifications@linkedin.com",
      domainId: "linkedin.com",
      email: "notifications@linkedin.com",
      name: "LinkedIn Notifications",
      totalCount: 200,
      unsubscribeUrl: "https://linkedin.com/settings/notifications",
      unsubscribeMethod: "header",
    },
    {
      id: "messages@linkedin.com",
      domainId: "linkedin.com",
      email: "messages@linkedin.com",
      name: "LinkedIn Messages",
      totalCount: 85,
      unsubscribeUrl: "https://linkedin.com/settings/email",
      unsubscribeMethod: "header",
    },
    {
      id: "news@linkedin.com",
      domainId: "linkedin.com",
      email: "news@linkedin.com",
      name: "LinkedIn News",
      totalCount: 57,
      unsubscribeUrl: "https://linkedin.com/settings/news",
      unsubscribeMethod: "footer_link",
    },
  ],
  "notion.so": [
    {
      id: "updates@notion.so",
      domainId: "notion.so",
      email: "updates@notion.so",
      name: "Notion Updates",
      totalCount: 30,
      unsubscribeUrl: "https://notion.so/unsubscribe",
      unsubscribeMethod: "header",
    },
    {
      id: "mktg@notion.so",
      domainId: "notion.so",
      email: "mktg@notion.so",
      name: "Notion Marketing",
      totalCount: 15,
      unsubscribeUrl: "https://notion.so/unsubscribe",
      unsubscribeMethod: "footer_link",
    },
  ],
  "vercel.com": [
    {
      id: "notifications@vercel.com",
      domainId: "vercel.com",
      email: "notifications@vercel.com",
      name: "Vercel Notifications",
      totalCount: 22,
      unsubscribeMethod: "none",
    },
    {
      id: "changelog@vercel.com",
      domainId: "vercel.com",
      email: "changelog@vercel.com",
      name: "Vercel Changelog",
      totalCount: 10,
      unsubscribeUrl: "https://vercel.com/unsubscribe",
      unsubscribeMethod: "header",
    },
  ],
  "figma.com": [
    {
      id: "notifications@figma.com",
      domainId: "figma.com",
      email: "notifications@figma.com",
      name: "Figma Notifications",
      totalCount: 12,
      unsubscribeUrl: "https://figma.com/settings/notifications",
      unsubscribeMethod: "header",
    },
    {
      id: "newsletter@figma.com",
      domainId: "figma.com",
      email: "newsletter@figma.com",
      name: "Figma Newsletter",
      totalCount: 7,
      unsubscribeUrl: "https://figma.com/unsubscribe",
      unsubscribeMethod: "footer_link",
    },
  ],
};

export const mockThreads: Record<string, EmailThread[]> = {
  "ravi@google.com": [
    {
      id: "thread-1",
      handleId: "ravi@google.com",
      subject: "Q3 Product Launch - Status Update",
      hasAttachments: false,
      labels: ["important"],
      messages: [
        {
          id: "msg-1",
          sender: "Ravi Krishnan",
          senderEmail: "ravi@google.com",
          bodyText: "Hey team! Quick update on the Q3 product launch timeline. We're on track for the July 15th deadline. The engineering team has completed the core feature set, and QA is running final regression tests this week.",
          sentAt: new Date("2026-04-27T08:30:00"),
          isMe: false,
          attachments: [],
        },
        {
          id: "msg-2",
          sender: "You",
          senderEmail: "me@example.com",
          bodyText: "That's great to hear, Ravi! Can you share the latest metrics from the beta? I'd love to see the user engagement numbers before we finalize the go-to-market strategy.",
          sentAt: new Date("2026-04-27T08:45:00"),
          isMe: true,
          attachments: [],
        },
        {
          id: "msg-3",
          sender: "Ravi Krishnan",
          senderEmail: "ravi@google.com",
          bodyText: "Absolutely! Here's a quick summary:\n\n- DAU: 12,500 (up 34% from beta start)\n- Session duration: 8.2 min avg\n- NPS Score: 72\n- Feature adoption: 89% for core features\n\nI'll send the full report by EOD. The team is really excited about the momentum!",
          sentAt: new Date("2026-04-27T09:10:00"),
          isMe: false,
          attachments: [],
        },
        {
          id: "msg-4",
          sender: "You",
          senderEmail: "me@example.com",
          bodyText: "Those numbers look solid. Let's schedule a review meeting with the exec team for Thursday. I want to make sure we have buy-in on the launch budget before we commit to the ad spend.",
          sentAt: new Date("2026-04-27T09:30:00"),
          isMe: true,
          attachments: [],
        },
        {
          id: "msg-5",
          sender: "Ravi Krishnan",
          senderEmail: "ravi@google.com",
          bodyText: "Done! I've sent calendar invites for Thursday 2pm. I'll prep a concise deck covering the key metrics and our ask for the budget increase. Should we also include the competitive analysis Sarah's team put together?",
          sentAt: new Date("2026-04-27T09:45:00"),
          isMe: false,
          attachments: [],
        },
      ],
    },
    {
      id: "thread-2",
      handleId: "ravi@google.com",
      subject: "Design Review Feedback",
      hasAttachments: true,
      labels: [],
      messages: [
        {
          id: "msg-6",
          sender: "Ravi Krishnan",
          senderEmail: "ravi@google.com",
          bodyText: "Hey, I've reviewed the latest design mockups. Overall the direction is great, but I have a few suggestions:\n\n1. The navigation feels a bit cluttered on mobile\n2. Can we try a bolder CTA color?\n3. The onboarding flow needs more whitespace\n\nLet me know when you're free to discuss!",
          sentAt: new Date("2026-04-25T14:00:00"),
          isMe: false,
          attachments: [
            { id: "att-1", name: "design-review-notes.pdf", size: "2.4 MB", type: "pdf" },
          ],
        },
        {
          id: "msg-7",
          sender: "You",
          senderEmail: "me@example.com",
          bodyText: "Thanks for the thorough review! I agree on all points. I'll have the design team iterate on these by Wednesday. The mobile nav was also flagged by our UX researcher, so it's definitely priority #1.",
          sentAt: new Date("2026-04-25T14:30:00"),
          isMe: true,
          attachments: [],
        },
      ],
    },
  ],
  "priya@google.com": [
    {
      id: "thread-3",
      handleId: "priya@google.com",
      subject: "Invoice #INV-2026-0892",
      hasAttachments: true,
      labels: ["invoice"],
      messages: [
        {
          id: "msg-8",
          sender: "Priya Sharma",
          senderEmail: "priya@google.com",
          bodyText: "Hi, please find attached the invoice for the cloud infrastructure services rendered in April 2026. Payment is due within 30 days.\n\nTotal: $4,250.00\nInvoice #: INV-2026-0892\nDue Date: May 27, 2026",
          sentAt: new Date("2026-04-20T10:00:00"),
          isMe: false,
          attachments: [
            { id: "att-2", name: "INV-2026-0892.pdf", size: "156 KB", type: "pdf" },
          ],
        },
        {
          id: "msg-9",
          sender: "You",
          senderEmail: "me@example.com",
          bodyText: "Received, Priya. I'll get this processed through our AP system this week. Quick question - can we set up automatic payments for future invoices?",
          sentAt: new Date("2026-04-20T11:15:00"),
          isMe: true,
          attachments: [],
        },
        {
          id: "msg-10",
          sender: "Priya Sharma",
          senderEmail: "priya@google.com",
          bodyText: "Absolutely! I'll send you the auto-pay enrollment form. It typically takes one billing cycle to activate, so the May invoice would still be manual. Starting June, everything will be automated.",
          sentAt: new Date("2026-04-20T14:00:00"),
          isMe: false,
          attachments: [],
        },
      ],
    },
  ],
  "jack@google.com": [
    {
      id: "thread-4",
      handleId: "jack@google.com",
      subject: "Lunch tomorrow?",
      hasAttachments: false,
      labels: [],
      messages: [
        {
          id: "msg-11",
          sender: "Jack Thompson",
          senderEmail: "jack@google.com",
          bodyText: "Hey! Want to grab lunch tomorrow? There's a new ramen place that opened near the office. I heard their tonkotsu is amazing.",
          sentAt: new Date("2026-04-26T16:30:00"),
          isMe: false,
          attachments: [],
        },
        {
          id: "msg-12",
          sender: "You",
          senderEmail: "me@example.com",
          bodyText: "Sounds perfect! Let's do 12:30? I've been craving good ramen for weeks.",
          sentAt: new Date("2026-04-26T17:00:00"),
          isMe: true,
          attachments: [],
        },
      ],
    },
  ],
  "notifications@google.com": [
    {
      id: "thread-5",
      handleId: "notifications@google.com",
      subject: "Security alert: New sign-in from Chrome on Windows",
      hasAttachments: false,
      labels: ["security"],
      messages: [
        {
          id: "msg-13",
          sender: "Google Security",
          senderEmail: "notifications@google.com",
          bodyText: "Your Google Account was just signed in to from a new Windows device. If this was you, no further action is needed.\n\nDevice: Windows 11\nLocation: San Francisco, CA\nTime: Apr 27, 2026, 7:30 AM PST\n\nIf you don't recognize this activity, please secure your account immediately.",
          sentAt: new Date("2026-04-27T07:30:00"),
          isMe: false,
          attachments: [],
        },
      ],
    },
  ],
  "cloud-noreply@google.com": [
    {
      id: "thread-6",
      handleId: "cloud-noreply@google.com",
      subject: "Cloud billing summary - April 2026",
      hasAttachments: true,
      labels: ["billing"],
      messages: [
        {
          id: "msg-14",
          sender: "Google Cloud",
          senderEmail: "cloud-noreply@google.com",
          bodyText: "Your Google Cloud billing summary for April 2026 is ready.\n\nTotal charges: $1,284.56\nCompute: $845.20\nStorage: $234.18\nNetworking: $156.34\nBigQuery: $48.84\n\nView your detailed billing report in the Cloud Console.",
          sentAt: new Date("2026-04-26T06:00:00"),
          isMe: false,
          attachments: [
            { id: "att-3", name: "billing-apr-2026.csv", size: "89 KB", type: "csv" },
          ],
        },
      ],
    },
  ],
  "notifications@github.com": [
    {
      id: "thread-7",
      handleId: "notifications@github.com",
      subject: "PR #342 merged: feat: add semantic search",
      hasAttachments: false,
      labels: [],
      messages: [
        {
          id: "msg-15",
          sender: "GitHub",
          senderEmail: "notifications@github.com",
          bodyText: "PR #342 has been merged into main by @alexis-dev.\n\nfeat: add semantic search\n\nThis PR adds semantic search capability using local embeddings. The feature uses transformers.js with the all-MiniLM model for generating embeddings locally.\n\n+482 additions, -23 deletions across 14 files",
          sentAt: new Date("2026-04-27T09:00:00"),
          isMe: false,
          attachments: [],
        },
      ],
    },
  ],
  "notifications@vercel.com": [
    {
      id: "thread-8",
      handleId: "notifications@vercel.com",
      subject: "Deployment failed: done-app production",
      hasAttachments: false,
      labels: ["alert"],
      messages: [
        {
          id: "msg-16",
          sender: "Vercel",
          senderEmail: "notifications@vercel.com",
          bodyText: "Your deployment to production failed.\n\nProject: done-app\nBranch: main\nError: Build failed - TypeScript compilation error in src/lib/store.ts:42\n\nPlease check the build logs for more details.",
          sentAt: new Date("2026-04-27T10:15:00"),
          isMe: false,
          attachments: [],
        },
      ],
    },
  ],
};

export const mockFolders: Folder[] = [
  { id: "folder-1", name: "Receipts", emailIds: [], domainIds: ["stripe.com"] },
  { id: "folder-2", name: "Invoices", emailIds: [], domainIds: [] },
  { id: "folder-3", name: "Newsletters", emailIds: [], domainIds: ["linkedin.com"] },
];

export const mockAIMessages: AIChatMessage[] = [
  {
    id: "ai-1",
    role: "assistant",
    content: "Hi! I'm your AI email assistant. I can help you find emails, summarize threads, or answer questions about your inbox. Try asking me something like \"Show me all invoices from last month\" or \"Summarize my emails from Google\".",
    timestamp: new Date("2026-04-27T08:00:00"),
  },
];

// Helper to get threads for any handle
export function getThreadsForHandle(handleId: string): EmailThread[] {
  return mockThreads[handleId] || [];
}

// Helper to get handles for domain
export function getHandlesForDomain(domainId: string): HandleGroup[] {
  return mockHandleGroups[domainId] || [];
}
